_name: network_test
data_loaders:
  _name: s3n.fetch_data
  dataset: 
    _name: s3n.loadfeafa_test
    data_dir: /home/wangccy/FEAFA2
  batch_size: 16
  num_workers: 0
  transform:
    _name: s3n.image_transform
    image_size: [448, 448]
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
  train_augmentation:
    horizontal_flip: 0.0
    random_crop:
      scale: [0.8, 1]
  test_augmentation:
    center_crop: 240
  test_image_size: 448
  train_splits:
    - train
  test_splits:
    - test
resume: "./saved/model_59.pt"
saved_path: "./output/pred.npy"
log_path: './logs/s3n.log'
model:
  _name: s3n.s3n
  mode: 'resnet50'
  num_classes: 24
  radius: 0.09
  radius_inv: 0.3
criterion:
  _name: s3n.prop_mse
optimizer:
  _name: s3n.sgd_optimizer
  lr: 0.01
  momentum: 0.9
  weight_decay: 1.0e-4
parameter:
  _name: s3n.finetune
  base_lr: 0.001
  groups:
    'classifier': 10.0
    'radius': 0.0001
    'filter': 0.0001
max_epoch: 60
device: cuda
use_data_parallel: yes
hooks:
  on_start_epoch:
    -
      _name: s3n.update_lr
      epoch_step: 40
  on_start_forward:
    -
      _name: s3n.three_stage
  on_end_epoch: 
    - 
      _name: s3n.print_state
      formats:
          - 'epoch: {epoch_idx}'
          - 'train_loss: {metrics[train_loss]:.4f}'
          - 'test_loss: {metrics[test_loss]:.4f}'
          - 'train_branch1_top1: {metrics[train_top1][branch_0]:.2f}%'        
          - 'train_branch2_top1: {metrics[train_top1][branch_1]:.2f}%'
          - 'train_branch3_top1: {metrics[train_top1][branch_2]:.2f}%'
          - 'train_branch4_top1: {metrics[train_top1][branch_3]:.2f}%'
          - 'test_branch1_top1: {metrics[test_top1][branch_0]:.2f}%'        
          - 'test_branch2_top1: {metrics[test_top1][branch_1]:.2f}%'
          - 'test_branch3_top1: {metrics[test_top1][branch_2]:.2f}%'
          - 'test_branch4_top1: {metrics[test_top1][branch_3]:.2f}%'
    -
      _name: s3n.checkpoint
      save_dir: None
      save_step: 1
